### ISSUE TITLE
migration to eslint

### ISSUE THREAD

**Issue by eankeen** [Standard-Structure/struct#12]
saw that this new project had a `tsconfig.json` - since that's been deprecated for a while now and the recommended approach is to use eslint, were you looking for any help do a simple migration? i can make a pr

**Comment by Cal-Hagner** [comment]
@rishiosaur @cjdenio What's your opinion on this? Sounds good to me!

**Comment by cjdenio** [comment]
Yep, sounds great!

**Comment by Cal-Hagner** [comment]
@eankeen Go for it! Thank you for reaching out!

**Comment by rishiosaur** [comment]
Yeah, I’m open to it. @eankeen If you’re tackling it, just make sure that you consult the Gluegun docs.
