### ISSUE TITLE
upgrade output target format

### ISSUE THREAD

**Issue by eankeen** [Standard-Structure/struct#16]
noticed the `tsconfig.json`'s target was set to `es5`. aside from creating unnecessary runtime overhead via regenerator runtime (all maintained node verions have supported async / await syntax for a while now), it's not really needed. 

i recommend we set the target to `ES2018` and set a `package.json` `engines` value to a minimum version of `10.18.1` (less than that and we'll have to polyfill `Object.prototype.values` for compatibility reasons) - i can create a pr for this

**Comment by Cal-Hagner** [comment]
@eankeen Doesn't your previous PR, #15, remove `tslint.json`?

**Comment by eankeen** [comment]
oh oops i meant to say `tsconfig.json`

**Comment by eankeen** [comment]
once i'm off mobile i'll edit the text

**Comment by Cal-Hagner** [comment]
As long as you're making sure that the CLI still functions (i.e. `gluegun` still functions), then I'm all for optimizing and quality control.
