### ISSUE TITLE
ensure `package.json` scripts are more cross platform

### ISSUE THREAD

**Issue by eankeen** [Standard-Structure/struct#17]
right now the `scripts` entries in the `package.json` are not cross platform (won't work on windows). (ex. shell-dependent glob behavior, bash / shell logical evaluation operators, use of shell / bash builtins etc.)., if needed i can clean this up an ensure a more consistent cross platform experience - can make a pr for this

**Comment by Cal-Hagner** [comment]
Just make sure that this doesn't break existing functionality (not that it should)!

**Comment by eankeen** [comment]
i'll start work on this once #12 is merged
