### ISSUE TITLE
Remove the use of * operator

### ISSUE THREAD

**Issue by rishiosaur** [Standard-Structure/struct#34]
I think the `*` operator makes all function importing very verbose; I think we should switch to direct imports.

**Comment by cjdenio** [comment]
Where is this?

**Comment by cjdenio** [comment]
Oh, I think I see. You're talking about this?
```ts
import * as os from 'os'
import * as fs from 'fs'
import * as path from 'path'
```

**Comment by rishiosaur** [comment]
Yep!

**Comment by rishiosaur** [comment]
I find named imports to lead to cleaner code.
