### ISSUE TITLE
Add Styling workflow to GitHub Actions

### ISSUE THREAD

**Issue by Cal-Hagner** [Standard-Structure/struct#9]
I can easily make a simple action that runs `npm run format` just to make sure that style is consistently enforced, and we would probably only run it on pushes to master. Do you guys think this is something that is worth adding?

@cjdenio @rishiosaur

**Comment by cjdenio** [comment]
Definitely!

**Comment by Cal-Hagner** [comment]
Alright, I'm off of my screens for the night, I have work bright and early tomorrow morning. I can add this as soon as I get up or one of you can add it tonight if you're so inclined.

**Comment by Matt-Gleich** [comment]
I'm gonna add it. Great idea!
